<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Report - {{ $pharmacy->name }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 14px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 24px; color: #1e40af; }
        .header p { margin: 5px 0 0; color: #666; font-size: 12px; }
        .summary-box { border: 1px solid #ddd; padding: 15px; margin-bottom: 30px; background-color: #f8fafc; border-radius: 5px; }
        .summary-box table { width: 100%; }
        .summary-box td { padding: 5px; }
        .summary-box .label { font-weight: bold; color: #64748b; font-size: 12px; text-transform: uppercase; }
        .summary-box .value { font-size: 18px; font-weight: bold; color: #0f172a; text-align: right; }
        .section-title { font-size: 16px; font-weight: bold; color: #334155; margin-bottom: 10px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; }
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .data-table th, .data-table td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
        .data-table th { background-color: #f1f5f9; font-size: 12px; color: #475569; text-transform: uppercase; }
        .data-table tr:nth-child(even) { background-color: #f8fafc; }
        .footer { text-align: center; margin-top: 50px; font-size: 10px; color: #94a3b8; }
    </style>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    fontFamily: { sans: ['Outfit', 'sans-serif'] },
                    colors: {
                        geo: { 900: '#0F172A', 800: '#1E293B', 700: '#1F2E2C', 600: '#2F7E6A', 500: '#63C6A7', 400: '#BFE8D6', 300: '#A0D8C4', 100: '#E9F7F2', 50: '#F8FAFC' }
                    }
                }
            }
        }
    </script></head>
<body>

    <div class="header">
        <h1>{{ $pharmacy->name }}</h1>
        <p>{{ $pharmacy->address }}</p>
        <p>Sales Report as of {{ $date }}</p>
    </div>

    <div class="summary-box">
        <table>
            <tr>
                <td class="label">Total Delivered Orders:</td>
                <td class="value">{{ $ordersCount }}</td>
            </tr>
            <tr>
                <td class="label">Total Net Revenue:</td>
                <td class="value" style="color: #059669;">P{{ number_format($totalRevenue, 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="section-title">Top 10 Fast-Moving Medicines</div>
    
    @if($topMedicines->isEmpty())
        <p style="text-align: center; color: #64748b; font-style: italic; margin-top: 20px;">No sales data available yet.</p>
    @else
        <table class="data-table">
            <thead>
                <tr>
                    <th style="width: 10%; text-align: center;">Rank</th>
                    <th style="width: 40%;">Brand Name</th>
                    <th style="width: 30%;">Generic Name</th>
                    <th style="width: 20%; text-align: right;">Total Units Sold</th>
                </tr>
            </thead>
            <tbody>
                @foreach($topMedicines as $index => $item)
                <tr>
                    <td style="text-align: center; font-weight: bold; color: #64748b;">#{{ $index + 1 }}</td>
                    <td style="font-weight: bold;">{{ $item->medicine->brand_name ?? 'N/A' }}</td>
                    <td>{{ $item->medicine->generic_name }}</td>
                    <td style="text-align: right; font-weight: bold; color: #0f172a;">{{ $item->total_sold }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by GEORX Medicine Hub Portal on {{ date('Y-m-d H:i:s') }}
    </div>

</body>
</html>
